config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    get "myproducts", on: :collection
    resources :purchases, only: [:create]
    resources :reviews, only: %i[new create]
  end

  resources :reviews, only: :destroy
  get "mypurchases" => 'purchases#mypurchases'

  resource :cart, only: [:show, :destroy] do
    post 'add_product_to_cart', on: :collection
    post 'purchase_items', on: :member
  end

  resources :cart_items, only: [:edit, :update, :destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="z-3 alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="z-3 alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4 about-us">
        <h3 class="first-h3">Sobre Nós</h3>
        <p class= "paragraph-market"> No My Chemicals Marketplace fornecemos uma ampla gama de produtos químicos de alta qualidade para atender às necessidades de diversos setores.
         Nosso compromisso é oferecer uma seleção diversificada de substâncias químicas essenciais, desde aplicações agropecuária até uso industrial.
         Com uma plataforma intuitiva e serviços confiáveis, estamos aqui para impulsionar seu negócio com segurança e eficiência.
         Explore nosso Marketplace agora e descubra como podemos ser seu parceiro confiável em soluções químicas.</p>
      </div>
      <div class="col-md-4">
        <h3 class="first-h3">Links Úteis</h3>
        <ul class="list-unstyled">
          <li><%= link_to "Página Inicial", root_path %></li>
          <li><%= link_to "Meus produtos", myproducts_products_path %></li>
        <div class="footer-links">
          <h2 class="first-h2">Redes Sociais<h2>
          <a href="https://github.com/seuusuario" target="_blank" rel="noopener noreferrer"><i class="fab fa-github"></i></a>
          <a href="https://www.instagram.com/seuusuario/" target="_blank" rel="noopener noreferrer"><i class="fab fa-instagram"></i></a>
          <a href="https://www.facebook.com/seuusuario" target="_blank" rel="noopener noreferrer"><i class="fab fa-facebook"></i></a>
          <a href="https://twitter.com/seuusuario" target="_blank" rel="noopener noreferrer"><i class="fab fa-twitter"></i></a>
          <a href="https://www.linkedin.com/in/seuusuario" target="_blank" rel="noopener noreferrer"><i class="fab fa-linkedin"></i></a>
        </div>
        </ul>
      </div>
      <div class="col-md-4">
        <h3 class="first-h3">Contato</h3>
        <p>Endereço: Rua Benjamim Egas  193, São Paulo/SP</p>
        <p>Email: mychemicals@mychemical.com</p>
        <p>Telefone: (11) 4547-7890</p>
      </div>
      <div class="map" id="map"></div>

<script>
  mapboxgl.accessToken = "pk.eyJ1Ijoiam9yZGFubzg4IiwiYSI6ImNsc2x4OWdvZjBkOTUyanNjOXRtZno4YnkifQ.9TVAMKmkrFEmnXjmIah2aQ";
  // const locate=document.querySelector("#map");
  var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [-46.687, -23.565],
    zoom: 15
  });


  new mapboxgl.Marker()
    .setLngLat([-46.687, -23.565])
    .addTo(map);
   // locate.appendChild
</script>
<script src='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.js'></script>


    </div>
    <hr>
    <div class="row">
      <div class="col-md-12">
        <p class="text-center">&copy; <%= Time.now.year %> My Chemicals Marketplace. Todos os direitos reservados.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon py-0">
  <div class="container-fluid">
    <%= link_to "/products", class: "navbar-brand" do %>
      <h1 class="navbar-text">MyChemicals <i class="fa-solid fa-wheat-awn"></i></h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class=" btn nav-account p-2" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Bem vindo <%= current_user.first_name.titleize %> <i class="fa-solid fa-caret-down"></i>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Meu carrinho", cart_path, class: "dropdown-item" %>
              <%= link_to "Meus produtos", "/products/myproducts", class: "dropdown-item" %>
              <%= link_to "Meus pedidos", mypurchases_path, class: "dropdown-item" %>
              <%= link_to "Minha conta", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: " btn nav-account"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>