config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    get "myproducts", on: :collection
    resources :purchases, only: [:create]
    resources :reviews, only: %i[new create]
  end

  resources :reviews, only: :destroy
  get "mypurchases" => 'purchases#mypurchases'

  resource :cart, only: [:show, :destroy] do
    post 'add_product_to_cart', on: :collection
    post 'purchase_items', on: :member
  end

  resources :cart_items, only: [:edit, :update, :destroy]
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_cart
  end

  def add_product_to_cart
    product = Product.find(params[:product_id])
    quantity = params[:quantity].to_i
    @cart = current_cart

    new_item = @cart.cart_items.find_or_initialize_by(product: product)

    new_item.quantity ||= 0
    new_item.quantity += quantity

    if new_item.quantity > product.quantity
      redirect_to product_path(product), alert: 'Not enough product quantity available.'
    elsif new_item.save
      redirect_to cart_path, notice: 'Product added to cart.'
    else
      redirect_to product_path(product), alert: 'There was a problem adding the product to the cart.'
    end
  end

  def purchase_items
    @cart = current_cart
    insufficient_stock = false

    ActiveRecord::Base.transaction do
      @cart.cart_items.each do |cart_item|
        @product = cart_item.product
        new_quantity = @product.quantity - cart_item.quantity

        if new_quantity.negative?

          insufficient_stock = true
          raise ActiveRecord::Rollback
        end

        @product.update!(quantity: new_quantity)
        Purchase.create!(user: current_user, product: @product, quantity: cart_item.quantity, date_purchase: Time.zone.now)
      end
      @cart.destroy!
    end

    if insufficient_stock

      flash[:alert] = 'Sorry, there was not enough stock for one or more products.'
      redirect_to cart_path
    else

      session[:cart_id] = nil

      redirect_to mypurchases_path, notice: 'Thank you for your purchase!'
    end
  rescue ActiveRecord::RecordInvalid => e
    Rails.logger.error("Purchase failed due to validation error: #{e.message}")
    flash[:alert] = 'Sorry, there was a problem with your purchase.'
    redirect_to cart_path
  end

  def destroy
    @cart = current_cart
    if @cart
      @cart.destroy
      session[:cart_id] = nil
      redirect_to root_path, notice: 'Cart emptied successfully.'
    else
      redirect_to root_path, alert: 'No cart found to empty.'
    end
  end

  private

  def current_cart
    current_user.cart ||= Cart.create(user: current_user)
  end
end

app/views/carts/show.html.erb
<div class="container mt-4">
  <h1 class="page-title">Seu carrinho</h1>

  <% if @cart.present? && @cart.cart_items.any? %>
    <div class="cards">
      <% @cart.cart_items.each do |cart_item| %>
        <div class="card-product">
          <% if cart_item.product.photo.attached? %>
            <%= cl_image_tag cart_item.product.photo.key, height: 300, width: 400, crop: :fill %>
          <% else %>
            <%= image_tag Faker::LoremFlickr.image(size: "70x70", search_terms: ['fertilizer'])%>
          <% end %>
            <div class="card-product-infos">
              <h2><%= cart_item.product.name %></h2>
              <p>Estoque: <%= cart_item.product.quantity %></p>
              <p>Quantidade: <%= cart_item.quantity %></p>
              <p>R$ <%= cart_item.product.price %></p>
              <p>Total R$ <%= cart_item.product.price*cart_item.quantity %></p>
            </div>
            <%= form_with(model: cart_item, local: true) do |form| %>
              <div class="field">
                <%= form.label :quantity %>
                <%= form.number_field :quantity, min: 1 %>
              </div>
              <div class="actions m-2">
                <%= form.submit "Atualizar quantidade", class: "btn-blue" %>
              </div>
            <% end %>
            <%= link_to cart_item_path(cart_item),  data: {turbo_method: :delete, turbo_confirm: "Tem certeza?"}, class:'btn-card-dlt ma mx-2' do  %>
              <i class="fa-solid fa-trash-can"></i>
            <%end %>
        </div>
        <% end %>
    </div>
  <% else %>
    <p>Seu carrinho está vazio.</p>
  <% end %>
  <%# <div class="d-grid"> %>
      <%= link_to 'Continuar Comprando', products_path, class: "btn-blue" %>
      <%= button_to 'Esvaziar Carrinho', cart_path(@cart), method: :delete, data: { confirm: 'Limpar carrinho?' }, class: 'btn-yellow my-2' %>
      <%= button_to "Comprar", purchase_items_cart_path, method: :post, class: "btn-green mb-2", data: { confirm: "Finalizar a compra?" } %>
  <%# </div> %>
</div>