config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    get "myproducts", on: :collection
    resources :purchases, only: [:create]
    resources :reviews, only: %i[new create]
  end

  resources :reviews, only: :destroy
  get "mypurchases" => 'purchases#mypurchases'

  resource :cart, only: [:show, :destroy] do
    post 'add_product_to_cart', on: :collection
    post 'purchase_items', on: :member
  end

  resources :cart_items, only: [:edit, :update, :destroy]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :purchases
  has_many :cart_items
  has_many :reviews, dependent: :destroy
  has_many :carts, through: :cart_items
  has_one_attached :photo
  validates :name, :price, :description, :photo, presence: true
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    if params[:search].present? && params[:search][:query].present?
      @products = Product.where("name ILIKE :query OR description ILIKE :query", query: "%#{params[:search][:query]}%")
    else
      @products = Product.all
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    if @product.save
      redirect_to myproducts_products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.purchases.count.positive?
      flash[:alert] = "Product has already been purchased and cannot be edited."
    end
    if @product.update(product_params)
      redirect_to myproducts_products_path
      flash[:alert] = "Product edited successfully."
    else
      render :edit
    end
  end

  def myproducts
    @products = current_user.products
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to myproducts_products_path, status: :see_other
  end

  private

  # Only allow a product of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :price, :description, :quantity, :photo)
  end
end

app/views/products/_product-info.html.erb
<div class="card-container">
  <div class="product-card">
    <div class="product-image m-2">
      <% if product.photo.attached? %>
        <%= cl_image_tag product.photo.key, height: 400, width: 400, crop: :fill %>
      <% else %>
        <%= image_tag Faker::LoremFlickr.image(size: "400x400", search_terms: ['fertilizer']) ,class:'img-fluid'%>
      <% end %>
    </div>
    <div class="product-info p-2 my-2 d-flex justify-content-between flex-column">
      <div class="d-flex flex-column align-items-start">
        <h2 class="product-title"><%= @product.name %></h2>
        <p class="product-description"><%= @product.description %></p>
        <p class="product-description">Estoque: <%= @product.quantity %></p>
        <span class="product-price">R$ <%= sprintf("%.2f", @product.price) %></span>
          <p>Vendedor: <%= @product.user.first_name.titleize %> <%= @product.user.last_name.titleize %></p>
        <% if current_user != @product.user %>
          <div class="mt-5 pt-5">
            <%= form_with url: add_product_to_cart_cart_path do |form| %>
              <%= form.hidden_field :product_id, value: @product.id %>
              <%= form.number_field :quantity, value: 1, min: 1 %>
              <%= form.submit "Adicionar ao carrinho", class: "btn-yellow" %>
            <% end %>
            <div class="pt-3">
            <%= link_to "Comprar agora", product_purchases_path(product), data: {turbo_method: :post, turbo_confirm: "Confirmar compra?"} , class: "btn-green" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card-container-review">
  <div class="card col-5 mx-5">
    <div class="card-header">
      Avaliações
    </div>
    <ul class="list-group list-group-flush">
    <% @product.reviews.each do |review| %>
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
          <% if review.user %>
            <div class="fw-bold mb-2">Comentário de <%= review.user.first_name %> <%= review.user.last_name %>:</div>
          <% else %>
            <div class="fw-bold mb-2">Usuário anônimo:</div>
          <% end %>
          <p>- <%= review.content %></p>
        </div>
        <span class="badge bg-primary"><% review.rating.times do %> <i class="fa-solid fa-star"></i> <% end %> </span>
        <% if current_user == review.user %>
          <%= link_to review_path(review), data: {turbo_method: :delete, turbo_confirm: "Apagar Avaliação?"}, class: "btn bg-transparent" do %><i class="fa-solid fa-trash"></i><% end %>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>

  <div class="card shadow-sm bg-white col-6">
  <h2 class="m-3">Adicionar nova Avaliação?</h2>
    <div class="m-3">
      <%= simple_form_for [@product, @review] do |f| %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Avalie este produto", input_html: {data: {controller: "star-rating"}} %>
        <%= f.input :content, label: "Avaliação.."%>
        <%= f.submit "Enviar avaliação", class: "btn-login" %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<%= link_to product_path(product) do %>
  <div class="card-product">
    <% if product.photo.attached? %>
      <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <%= image_tag Faker::LoremFlickr.image(size: "70x70", search_terms: ['fertilizer'])%>
    <% end %>
    <div class="card-product-infos">
      <h2><%= product.name %></h2>
      <p>R$ <%= sprintf("%.2f", product.price) %></p>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <div class="form-shape col-md-6 mx-auto">
    <h1 class="form-title">Editar <%= @product.name %></h1>
    <%= simple_form_for @product do |f| %>
      <%= f.input :name, label: "Nome" %>
      <%= f.input :quantity, label: "Quantidade" %>
      <%= f.input :price, label: "Preço" %>
      <%= f.input :description, label: "Descrição" %>
      <%= f.button :submit, "Atualizar Produto", class:'btn-update-product mb-4' %>
    <% end %>
    <%= link_to 'Voltar', myproducts_products_path, class:'btn-back-to-my-products'%>
  </div>
</div>

app/views/products/index.html.erb
<div class="container py-4">
  <div class="banner">
    <h1>Encontre o que você precisa para a sua fazenda</h1>
    <%= simple_form_for :search, url: root_path, method: :get do |f| %>
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="search[query]" id="search_query" />
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i> Buscar
        </button>
      </div>
    <% end %>
  </div>
  <div class="cards">
    <div class="row">
      <% @products.each do |product| %>

          <div class="col-4">
            <%= render("product", product: product)  %>
          </div>

        <% end %>
    </div>
  </div>
</div>

app/views/products/myproducts.html.erb
<div class="container mt-4">
  <h1 class="page-title">Seus produtos</h1>
  <%= link_to new_product_path, class: "btn-new-product" do %>
  <i class="fa-solid fa-circle-plus"></i>
  <% end %>
  <div class="cards">
    <% @products.each do |product| %>
      <div class="card-product">
        <% if product.photo.attached? %>
          <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <%= image_tag Faker::LoremFlickr.image(size: "70x70", search_terms: ['fertilizer'])%>
        <% end %>
        <div class="card-product-infos">
          <h2><%= product.name %></h2>
          <p><%= product.description.truncate(50) %></p>
          <p>Estoque: <%= product.quantity %></p>
          <p>R$ <%= product.price %></p>
        </div>
          <div class="product-btn d-flex justify-content-end align-self-end mb-2">
            <% if product.purchases.count == 0 %>
              <%= link_to 'Edit', edit_product_path(product), class:'btn-card-edit ma' %>
              <%= link_to product_path(product),  data: {turbo_method: :delete, turbo_confirm: "Confirma exclusão de Produto?"}, class:'btn-card-dlt ma' do  %>
              <i class="fa-solid fa-trash-can"></i>
              <%end %>
    <% end %>
</div>
</div>
<% end %>
</div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="form-shape col-md-6 mx-auto">
    <h1 class="form-title">Cadastrar novo produto</h1>
    <%= simple_form_for @product do |f| %>
      <%= f.input :name, label_html: { class: "label-form" }, label: "Nome" %>
      <%= f.input :price, label: "Preço" %>
      <%= f.input :description, label: "Descrição" %>
      <%= f.input :quantity, label: "Quantidade" %>
      <%= f.input :photo, as: :file, label: "Imagem" %>
      <%= f.button :submit, class: "my-2 btn-login" %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<%= render("product-info", product: @product) %>